/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nob.Titles;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author mario
 */
public class NobiliarquicTiles extends javax.swing.JFrame {

    
    String vector[] = {"Empty","Empty","Empty","Empty","Empty","Empty","Empty","Empty",
                       "Empty","Empty","Empty","Empty","Empty","Empty","Empty","Empty"};
    String emp = "Empty";
    DefaultListModel listakari = new DefaultListModel();
    
    //Vá em Model e custom code e ponha "lista" para determinar o inserção de dados.
    int select = 0;
    /**
     * Creates new form NobiliarquicTiles
     */
    public NobiliarquicTiles() {
        initComponents();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(/*vector[c]*/ emp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnImperador = new javax.swing.JButton();
        btnGDuque = new javax.swing.JButton();
        btnDuque = new javax.swing.JButton();
        btnMarques = new javax.swing.JButton();
        btnChatelain = new javax.swing.JButton();
        btnConde = new javax.swing.JButton();
        btnCavaleiro = new javax.swing.JButton();
        btnLord = new javax.swing.JButton();
        btnBarao = new javax.swing.JButton();
        btnVisconde = new javax.swing.JButton();
        btnEarl = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstThisIsSparta = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblThisIsSparta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Insert Name:");

        btnImperador.setText("Imperador");
        btnImperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImperadorActionPerformed(evt);
            }
        });

        btnGDuque.setText("Grão-Duque");
        btnGDuque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGDuqueActionPerformed(evt);
            }
        });

        btnDuque.setText("Duque");
        btnDuque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuqueActionPerformed(evt);
            }
        });

        btnMarques.setText("Marquês");
        btnMarques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarquesActionPerformed(evt);
            }
        });

        btnChatelain.setText("Châtelain");
        btnChatelain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatelainActionPerformed(evt);
            }
        });

        btnConde.setText("Conde");
        btnConde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCondeActionPerformed(evt);
            }
        });

        btnCavaleiro.setText("Cavaleiro");
        btnCavaleiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCavaleiroActionPerformed(evt);
            }
        });

        btnLord.setText("Lord");
        btnLord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLordActionPerformed(evt);
            }
        });

        btnBarao.setText("Barão");
        btnBarao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaraoActionPerformed(evt);
            }
        });

        btnVisconde.setText("Visconde");
        btnVisconde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViscondeActionPerformed(evt);
            }
        });

        btnEarl.setText("Earl");
        btnEarl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEarlActionPerformed(evt);
            }
        });

        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        lstThisIsSparta.setModel(listakari);
        lstThisIsSparta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstThisIsSpartaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstThisIsSparta);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Reino Karimasênico");

        jLabel3.setText("Posição da Lista:");

        lblThisIsSparta.setText("[0]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnOrdenar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnImperador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGDuque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDuque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMarques, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChatelain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnCavaleiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBarao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVisconde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEarl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblThisIsSparta)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblThisIsSparta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnImperador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGDuque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDuque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMarques)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChatelain))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEarl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVisconde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBarao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCavaleiro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConde)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOrdenar)))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImperadorActionPerformed
        // TODO add your handling code here:
        
        vector[select] = "Karalius " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
        
    }//GEN-LAST:event_btnImperadorActionPerformed

    private void btnGDuqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGDuqueActionPerformed
        // TODO add your handling code here:
        
        vector[select] = "Didysis Kunigaikštis " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnGDuqueActionPerformed

    private void btnDuqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuqueActionPerformed
        // TODO add your handling code here:
        
        vector[select] = "Hercogas " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnDuqueActionPerformed

    private void btnMarquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarquesActionPerformed
        // TODO add your handling code here:
        vector[select] = "Markizas " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnMarquesActionPerformed

    private void btnChatelainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatelainActionPerformed
        // TODO add your handling code here:
        vector[select] = "Šatelenas " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnChatelainActionPerformed

    private void btnCondeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCondeActionPerformed
        // TODO add your handling code here:
        vector[select] = "Grafas " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnCondeActionPerformed

    private void btnEarlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEarlActionPerformed
        // TODO add your handling code here:
        vector[select] = "Erlas " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnEarlActionPerformed

    private void btnViscondeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViscondeActionPerformed
        // TODO add your handling code here:
        vector[select] = "Vikontas " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnViscondeActionPerformed

    private void btnBaraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaraoActionPerformed
        // TODO add your handling code here:
        vector[select] = "Baronas " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnBaraoActionPerformed

    private void btnLordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLordActionPerformed
        // TODO add your handling code here:
        vector[select] = "Viešpatie " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnLordActionPerformed

    private void btnCavaleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCavaleiroActionPerformed
        // TODO add your handling code here:
        vector[select] = "Riteris " + txtName.getText();
        listakari.removeAllElements();
        
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnCavaleiroActionPerformed

    private void lstThisIsSpartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstThisIsSpartaMouseClicked
        // TODO add your handling code here:
         select = lstThisIsSparta.getSelectedIndex();
        lblThisIsSparta.setText("[" + select + "]"); //Pula o erro do String-INT
    }//GEN-LAST:event_lstThisIsSpartaMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        if (vector.equals("")){
            Arrays.fill(vector, emp);
        };
        vector[select] = "Empty";
        listakari.removeAllElements();
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
        //Ordena um valor
        Arrays.sort(vector);
        
        if (vector.equals("")){
            Arrays.fill(vector, emp);
        };
        listakari.removeAllElements();
        for(int c = 0; c < vector.length; c++){
            listakari.addElement(vector[c]);
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NobiliarquicTiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NobiliarquicTiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NobiliarquicTiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NobiliarquicTiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NobiliarquicTiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarao;
    private javax.swing.JButton btnCavaleiro;
    private javax.swing.JButton btnChatelain;
    private javax.swing.JButton btnConde;
    private javax.swing.JButton btnDuque;
    private javax.swing.JButton btnEarl;
    private javax.swing.JButton btnGDuque;
    private javax.swing.JButton btnImperador;
    private javax.swing.JButton btnLord;
    private javax.swing.JButton btnMarques;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnVisconde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblThisIsSparta;
    private javax.swing.JList<String> lstThisIsSparta;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
