/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kari7.arrancomb;

/**
 *
 * @author kari7
 */
public class ArranComb extends javax.swing.JFrame {



    /**
     * Creates new form ArranComb
     */
    public ArranComb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnFatN = new javax.swing.JSpinner();
        spnFatP = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        sepArr = new javax.swing.JSeparator();
        lblArrN1 = new javax.swing.JLabel();
        lblArrN2 = new javax.swing.JLabel();
        lblArrP1 = new javax.swing.JLabel();
        sepComb = new javax.swing.JSeparator();
        lblCombN1 = new javax.swing.JLabel();
        lblCombN2 = new javax.swing.JLabel();
        lblCombP1 = new javax.swing.JLabel();
        lblCombP2 = new javax.swing.JLabel();
        lblArrEquals = new javax.swing.JLabel();
        lblCombEquals = new javax.swing.JLabel();
        lblArrResult = new javax.swing.JLabel();
        lblCombResult = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fakultät N:");

        jLabel2.setText("Fakultät P:");

        jLabel3.setText("Permutation:");

        spnFatN.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        spnFatN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnFatNStateChanged(evt);
            }
        });

        spnFatP.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        spnFatP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnFatPStateChanged(evt);
            }
        });

        jLabel4.setText("Kombination:");

        lblArrN1.setText("0!");

        lblArrN2.setText("(0 - ");

        lblArrP1.setText("0)!");

        lblCombN1.setText("0!");

        lblCombN2.setText("(0 - ");

        lblCombP1.setText("0! * ");

        lblCombP2.setText("0)!");

        lblArrEquals.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblArrEquals.setText("=");

        lblCombEquals.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCombEquals.setText("=");

        lblArrResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblArrResult.setForeground(new java.awt.Color(255, 102, 0));
        lblArrResult.setText("1");

        lblCombResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCombResult.setForeground(new java.awt.Color(0, 51, 255));
        lblCombResult.setText("1");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Polycarp Breite Grube");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel5.setText("Permutations und Kombinationsrechner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(59, 59, 59)
                            .addComponent(lblArrN1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(spnFatP, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(spnFatN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addComponent(lblArrN2)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblArrP1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblCombP1)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblCombN2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblCombP2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(sepArr, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sepComb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(38, 38, 38)
                                                    .addComponent(lblCombN1)))
                                            .addGap(82, 82, 82)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblCombEquals)
                                                .addComponent(lblArrEquals))
                                            .addGap(67, 67, 67)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblArrResult)
                                                .addComponent(lblCombResult))))))
                            .addGap(36, 36, 36)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(spnFatN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spnFatP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblArrN1))
                        .addGap(10, 10, 10)
                        .addComponent(sepArr, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArrEquals)
                            .addComponent(lblArrResult))
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArrN2)
                    .addComponent(lblArrP1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCombN1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sepComb, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCombEquals)
                                .addComponent(lblCombResult)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCombN2)
                            .addComponent(lblCombP2)
                            .addComponent(lblCombP1))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnFatNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnFatNStateChanged
        // TODO add your handling code here:
        int policlope = Integer.parseInt(spnFatN.getValue().toString());
        
        lblArrN1.setText(Integer.toString(policlope) + "!");
        lblArrN2.setText("( " + Integer.toString(policlope) + " -");
        lblCombN1.setText(Integer.toString(policlope) + "!");
        lblCombN2.setText("(" + Integer.toString(policlope) + " -");
    }//GEN-LAST:event_spnFatNStateChanged

    private void spnFatPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnFatPStateChanged
        // TODO add your handling code here:
        int policarpo = Integer.parseInt(spnFatP.getValue().toString());

        lblArrP1.setText(Integer.toString(policarpo) + ")!");
        lblCombP1.setText(Integer.toString(policarpo) + "! * ");
        lblCombP2.setText(Integer.toString(policarpo) + ")!");
    }//GEN-LAST:event_spnFatPStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //N e P
        int policlope1 = Integer.parseInt(spnFatN.getValue().toString());
        int policarpo1 = Integer.parseInt(spnFatP.getValue().toString());
        int fatorSubtrativo = policlope1 - policarpo1; //N-P
        
        int contador = fatorSubtrativo;
        double valorArranjado = 1d, arranjo, combination;
        int quaresma, quarentena;
        double covadonga = 1d, covalarga = 1d;
        quaresma = policlope1;
        quarentena = policarpo1;
        
        //N!
        while( quaresma >= 1){
            covadonga *= quaresma;
            quaresma--; //Fatorial começa diminundo
        }

        //P!
        while( quarentena >= 1){
            covalarga *= quarentena;
            quarentena--; //Fatorial começa diminundo
        }
        
        //Covadonga = N!
        //Covalarga = P!
        
        //Arranjo
        // (N! / (N-P)!)
        
        while(contador >= 1){
            valorArranjado *= contador;
            contador--;
        }
        arranjo = covadonga / valorArranjado;
        
        //Combinação
        // (N! / P! * (N-P)!)
        combination = covadonga / (covalarga * valorArranjado);
        
        
        lblArrResult.setText(Double.toString(arranjo));
        lblCombResult.setText(Double.toString(combination));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArranComb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArranComb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArranComb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArranComb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArranComb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblArrEquals;
    private javax.swing.JLabel lblArrN1;
    private javax.swing.JLabel lblArrN2;
    private javax.swing.JLabel lblArrP1;
    private javax.swing.JLabel lblArrResult;
    private javax.swing.JLabel lblCombEquals;
    private javax.swing.JLabel lblCombN1;
    private javax.swing.JLabel lblCombN2;
    private javax.swing.JLabel lblCombP1;
    private javax.swing.JLabel lblCombP2;
    private javax.swing.JLabel lblCombResult;
    private javax.swing.JSeparator sepArr;
    private javax.swing.JSeparator sepComb;
    private javax.swing.JSpinner spnFatN;
    private javax.swing.JSpinner spnFatP;
    // End of variables declaration//GEN-END:variables
}
