/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package math.jurocomposto;

import java.text.DecimalFormat;

/**
 *
 * @author Kari7
 */
public class juroComposto extends javax.swing.JFrame {

    /**
     * Creates new form juroComposto
     */
    public juroComposto() {
        initComponents();
    }

    
    public String juroCompostal(double cap, double tmp, double ind){
        double montante;
        double indexOne;
        double timerset;
        DecimalFormat warleyStrikesBack = new DecimalFormat("#.##");
        
        
        // C * (1+i)^t
        
        indexOne = 1 + ind;
        timerset = Math.pow(indexOne, tmp);
        montante = cap * timerset;
        
        return warleyStrikesBack.format(montante);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAnarcoCap = new javax.swing.JTextField();
        txtCotacao = new javax.swing.JTextField();
        txtYears = new javax.swing.JTextField();
        txtIndex = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnConvertMonthYear = new javax.swing.JButton();
        btnComposto = new javax.swing.JButton();
        btnCotacao = new javax.swing.JButton();
        labelFormula = new javax.swing.JLabel();
        lblAnarcoCap = new javax.swing.JLabel();
        lblMontante = new javax.swing.JLabel();
        btnConvertMonthYear_i = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Capital (US$/R$):");

        jLabel2.setText("Time (Months/Years):");

        jLabel3.setText("Taxes (% - Years/Month):");

        jLabel4.setText("Amount:");

        jLabel5.setText("Exchange rate (US$ to R$):");

        btnConvertMonthYear.setText("Months -> Years");
        btnConvertMonthYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertMonthYearActionPerformed(evt);
            }
        });

        btnComposto.setText("Compound interest");
        btnComposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompostoActionPerformed(evt);
            }
        });

        btnCotacao.setText("US$ -> R$");
        btnCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotacaoActionPerformed(evt);
            }
        });

        labelFormula.setText("Formula:");

        lblAnarcoCap.setText("<html>c * (1 + i)<sup>t</sup></html>");

        lblMontante.setText("R$ 0,00");

        btnConvertMonthYear_i.setText("Taxes p/ Year -> Taxes p/ Month");
        btnConvertMonthYear_i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertMonthYear_iActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(labelFormula)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAnarcoCap)
                                    .addComponent(txtYears)
                                    .addComponent(txtIndex, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConvertMonthYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConvertMonthYear_i, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 90, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAnarcoCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMontante))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnComposto, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnarcoCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnCotacao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConvertMonthYear)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertMonthYear_i))
                .addGap(14, 14, 14)
                .addComponent(btnComposto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnarcoCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFormula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblMontante))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotacaoActionPerformed
        // TODO add your handling code here:
        double dolar = Double.parseDouble(txtCotacao.getText());
        double real = Double.parseDouble(txtAnarcoCap.getText());
        double result;
        
        result = real * dolar;
        
        txtAnarcoCap.setText(Double.toString(result));
        
    }//GEN-LAST:event_btnCotacaoActionPerformed

    private void btnConvertMonthYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertMonthYearActionPerformed
        // TODO add your handling code here:
        double mes = Double.parseDouble(txtYears.getText());
        double ano;
        
        ano = mes / 12;
        
        txtYears.setText(Double.toString(ano));
        
    }//GEN-LAST:event_btnConvertMonthYearActionPerformed

    private void btnCompostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompostoActionPerformed
        // TODO add your handling code here:
        double capital = Double.parseDouble(txtAnarcoCap.getText());
        double tempo = Double.parseDouble(txtYears.getText());
        double index = Double.parseDouble(txtIndex.getText())/100;
        
        String compostal = juroCompostal(capital, tempo, index);
        DecimalFormat warlino = new DecimalFormat("#.####");
        DecimalFormat warleyArrumaNamoradaPeloAmorDeDeus = new DecimalFormat("#.##");
        
        lblAnarcoCap.setText("<html>" + warleyArrumaNamoradaPeloAmorDeDeus.format(capital) + " * ( 1 + "
                                      + warlino.format(index) +")<sup>" + warlino.format(tempo) 
                                      + "</sup></html>");
        lblMontante.setText("R$ " + compostal);
        
    }//GEN-LAST:event_btnCompostoActionPerformed

    private void btnConvertMonthYear_iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertMonthYear_iActionPerformed
        // TODO add your handling code here:
        double index = Double.parseDouble(txtIndex.getText());
        double ano;
        
        ano = index / 12;
        
        txtIndex.setText(Double.toString(ano));
    }//GEN-LAST:event_btnConvertMonthYear_iActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juroComposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juroComposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juroComposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juroComposto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juroComposto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComposto;
    private javax.swing.JButton btnConvertMonthYear;
    private javax.swing.JButton btnConvertMonthYear_i;
    private javax.swing.JButton btnCotacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelFormula;
    private javax.swing.JLabel lblAnarcoCap;
    private javax.swing.JLabel lblMontante;
    private javax.swing.JTextField txtAnarcoCap;
    private javax.swing.JTextField txtCotacao;
    private javax.swing.JTextField txtIndex;
    private javax.swing.JTextField txtYears;
    // End of variables declaration//GEN-END:variables
}
